### PR TITLE
Fix detection for Realtek 8723BU 7392:a611

### PR DESCRIPTION
**Pull request by mikefaille**

### CODE REVIEW

**Comment by lwfinger** [comment]
Thanks. I will send the equivalent patch to mainline.

**Comment by lwfinger** [comment]
I need one more thing to get that change into the kernel.
Do a 'cat /sys/kernel/debug/usb/devices' and post the output.

Thanks. My RTL8723BU does not have a BT part.

**Comment by mikefaille** [comment]
@lwfinger I'll do. Can we add my name as author  for the kernel's pull request ? Maybe, you can be the author. Or, I can prepare it for sure. It just depend your workflow. At least, if I could appear as contributor, I'll like it.

**Comment by lwfinger** [comment]
Sure, you can be the author of the kernel patch. I placed my name on the initial submission as I did not know your E-mail address, but that can be fixed in the next submission.

**Pull request merged**
